# Generated by Django 5.2.5 on 2025-11-30 16:14

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=orders.models.generate_tracking_number, max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('from_area', models.CharField(choices=[('capital', 'العاصمة'), ('salmiya', 'السالمية'), ('farwaniya', 'الفروانية'), ('hawalli', 'حولي'), ('jahra', 'الجهراء'), ('ahmadi', 'الأحمدي')], max_length=50)),
                ('to_area', models.CharField(choices=[('capital', 'العاصمة'), ('salmiya', 'السالمية'), ('farwaniya', 'الفروانية'), ('hawalli', 'حولي'), ('jahra', 'الجهراء'), ('ahmadi', 'الأحمدي')], max_length=50)),
                ('pickup_address', models.TextField(blank=True)),
                ('delivery_address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_type', models.CharField(choices=[('ultra', 'فوري (أقل من نصف ساعة)'), ('super', 'فائق السرعة (أقل من ساعة)'), ('express1', 'سريع جداً (1-3 ساعات)'), ('normal1', 'سريع (3-6 ساعات)'), ('normal2', 'عادي (6-12 ساعة)'), ('normal3', 'اقتصادي (12-18 ساعة)'), ('normal4', 'قياسي (18-24 ساعة)')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('knet', 'KNET')], default='cod', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('picked_up', 'تم الاستلام'), ('in_transit', 'في الطريق'), ('out_for_delivery', 'خرج للتسليم'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغى'), ('failed', 'فشل التوصيل')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('picked_up', 'تم الاستلام'), ('in_transit', 'في الطريق'), ('out_for_delivery', 'خرج للتسليم'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغى'), ('failed', 'فشل التوصيل')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
